apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: palworld-server
  name: palworld-server-pv
  namespace: palworld
spec:
  capacity:
    storage: 12Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: palworld-storage
  local:
    path: /mnt/palworld
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: palworld-server
  name: palworld-server-pvc
  namespace: palworld
spec:
  storageClassName: palworld-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
