apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
