# This is the values.yaml I used on my k3s raspberrypi cluster

# if you have a problem with serviceWeb Pods not building you might need to checkout this issue:
# https://github.com/MoJo2600/pihole-kubernetes/issues/230
ingress:
  # -- Generate a Ingress resource
  enabled: true

  # -- Specify an ingressClassName
  ingressClassName: nginx

  # -- Annotations for the ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    # virtualHost (default value is pi.hole) will be appended to the hosts
    - pihole-k3s.local.itcatgor.com

persistentVolumeClaim:
  enabled: true
  storageClass: "longhorn"

serviceWeb:
  # loadBalancerIP: 10.0.50.225
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  # type: LoadBalancer

serviceDns:
  loadBalancerIP: 10.0.50.225
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDhcp:
  # loadBalancerIP: 10.0.50.225
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  # type: LoadBalancer

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
    - 127.0.0.1
    - 8.8.8.8

adlists:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://easylist-downloads.adblockplus.org/advblock.txt
  - https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

#! use an existing secret in a prod env
adminPassword: "asd123asd"

doh:
  # -- set to true to enabled DNS over HTTPs via cloudflared
  enabled: true
  # -- name
  name: "cloudflared"
  # -- repository
  repository: "crazymax/cloudflared"
  tag: latest
  # -- Pull policy
  pullPolicy: IfNotPresent
  # -- Here you can pass environment variables to the DoH container, for example:
  envVars:
    TUNNEL_DNS_UPSTREAM: "https://1.1.1.2/dns-query,https://1.0.0.2/dns-query"

  # -- Probes configuration
  probes:
    # -- Configure the healthcheck for the doh container
    liveness:
      # -- set to true to enable liveness probe
      enabled: true
      # -- customize the liveness probe
      probe:
        exec:
          command:
            - nslookup
            - -po=5053
            - cloudflare.com
            - "127.0.0.1"
      # -- defines the initial delay for the liveness probe
      initialDelaySeconds: 60
      # -- defines the failure threshold for the liveness probe
      failureThreshold: 10
      # -- defines the timeout in secondes for the liveness probe
      timeoutSeconds: 5

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

extraEnvVars: { DNSMASQ_USER: "root" }
